
UPDATE products SET description = CASE title
WHEN 'Air Purifier HEPA' THEN 'Breathe cleaner, healthier air with this advanced room air purifier featuring a true H13 HEPA filter that captures 99.97% of airborne particles including dust, pollen, pet dander, and smoke. Designed for rooms up to 300 sq ft, it operates at whisper-quiet noise levels as low as 24dB, making it perfect for bedrooms and nurseries. The three-speed fan and sleep mode ensure optimal performance around the clock. The filter replacement indicator takes the guesswork out of maintenance.'
WHEN 'Bamboo Cutting Board Set' THEN 'Upgrade your kitchen prep with this set of three premium bamboo cutting boards in small, medium, and large sizes. Made from sustainably sourced moso bamboo, these boards are naturally antimicrobial, knife-friendly, and incredibly durable. The deep juice grooves prevent messy spills, while the non-slip silicone corners keep the board stable during cutting. Easy to clean and maintain, these boards are a beautiful and eco-friendly addition to any Indian kitchen.'
WHEN 'Cast Iron Tawa' THEN 'This traditional pre-seasoned cast iron tawa is a must-have for every Indian kitchen. Perfect for making rotis, parathas, dosas, and uttapams, the 12-inch cooking surface provides even heat distribution for perfectly cooked flatbreads every time. The cast iron naturally becomes more non-stick with use and adds beneficial iron to your food. The long wooden handle stays cool during cooking, and the tawa is compatible with gas, induction, and electric stoves.'
WHEN 'Ceramic Dinner Set 21pc' THEN 'Elevate your dining experience with this elegant 21-piece ceramic dinner set that serves a family of six. The set includes six dinner plates, six quarter plates, six bowls, two serving bowls, and one serving platter — everything you need for a complete table setting. The premium-grade ceramic features a beautiful floral pattern with gold trim that resists fading even after hundreds of dishwasher cycles. Microwave safe and lead-free for your familys safety.'
WHEN 'Cotton Bedsheet King' THEN 'Transform your bedroom into a luxurious retreat with this 300-thread-count king-size cotton bedsheet set. Includes one fitted bedsheet and two matching pillow covers in a sophisticated printed design. The 100% long-staple cotton fabric is pre-washed for immediate softness and gets even softer with every wash. The deep pockets accommodate mattresses up to 15 inches thick. Breathable and moisture-wicking, these sheets keep you comfortable through hot Indian summers and cool winters alike.'
WHEN 'Copper Water Bottle 1L' THEN 'Embrace the ancient Ayurvedic tradition of drinking water stored in copper with this beautifully handcrafted 1-liter copper water bottle. Made from 99.7% pure copper, it naturally purifies water and provides numerous health benefits including improved digestion, boosted immunity, and better joint health. The leak-proof screw cap and lacquer-free interior ensure you get the full benefits of copper-infused water. The elegant hammered finish makes it a stunning addition to your daily wellness routine.'
WHEN 'Mixer Grinder 750W' THEN 'This powerful 750-watt mixer grinder is an essential Indian kitchen appliance, perfect for grinding masalas, making chutneys, blending smoothies, and preparing batters. It comes with three stainless steel jars — a 1.5L liquidizing jar, 1L multi-purpose jar, and 0.4L chutney jar — to handle all your cooking needs. The overload protection circuit ensures motor safety, while the vacuum rubber feet keep it stable during operation. The sharp stainless steel blades deliver consistent, fine results every time.'
WHEN 'Non-Stick Cookware Set 5pc' THEN 'Complete your kitchen with this premium 5-piece non-stick cookware set that includes everything an Indian home cook needs: a fry pan, kadhai, saucepan, tawa, and casserole with glass lid. The advanced granite-finish non-stick coating is PFOA-free and requires minimal oil for healthy cooking. The heavy-gauge aluminum body ensures even heat distribution, while the cool-touch bakelite handles provide a comfortable, safe grip. Compatible with gas and induction cooktops. Dishwasher safe for easy cleanup.'
WHEN 'Scented Candle Set' THEN 'Create a warm, inviting ambiance in your home with this set of four premium soy wax scented candles. Each candle features a unique fragrance — Jasmine, Sandalwood, Rose, and Lavender — inspired by the rich aromatic traditions of India. Made from natural soy wax with cotton wicks, each candle burns cleanly for up to 25 hours without producing soot or toxic fumes. The beautiful frosted glass jars double as decorative pieces and can be reused as tealight holders after the candle is finished.'
WHEN 'Stainless Steel Thermos 500ml' THEN 'Keep your chai piping hot for up to 12 hours or your lassi ice cold for up to 24 hours with this premium double-wall vacuum insulated stainless steel thermos. The 500ml capacity is perfect for carrying your favorite beverages to work, college, or on road trips. The food-grade 18/8 stainless steel interior doesnt retain flavors or odors, and the leak-proof lid ensures your bag stays dry. The sleek matte finish with a sweat-proof exterior makes it comfortable to hold in any weather.'
WHEN 'Badminton Racket Pro' THEN 'Elevate your badminton game with this professional-grade graphite racket designed for competitive and recreational players alike. The lightweight graphite shaft provides exceptional power and control, while the isometric head shape enlarges the sweet spot for more forgiving shots. The pre-strung 24-lb tension strings deliver a perfect balance of power and accuracy. The cushioned PU grip absorbs sweat and vibration for comfortable, extended play. Comes with a full-length padded racket cover.'
WHEN 'Foam Roller Recovery' THEN 'Speed up your post-workout recovery with this high-density EVA foam roller featuring a textured surface that mimics the pressure of a deep tissue massage. The firm construction effectively relieves muscle tightness, knots, and trigger points in your back, legs, IT band, and glutes. At 18 inches long, it is perfect for home use, gym sessions, and travel. Use before workouts to warm up muscles or after exercise to reduce soreness and improve flexibility. Suitable for beginners and advanced athletes.'
WHEN 'Resistance Band Set' THEN 'Transform any space into your personal gym with this comprehensive set of five color-coded resistance bands offering different tension levels from extra-light to extra-heavy. Made from premium natural latex, these bands are durable, snap-resistant, and perfect for strength training, physical therapy, yoga, Pilates, and rehabilitation exercises. Each band is 5 feet long for versatile full-body workouts. The included exercise guide with 30 illustrated exercises helps you target every muscle group effectively.'
WHEN 'Skipping Rope Digital' THEN 'Take your cardio workouts to the next level with this digital skipping rope featuring a built-in LCD counter that tracks jumps, calories burned, and workout duration. The ergonomic anti-slip handles provide a comfortable grip even during intense sessions, while the adjustable 3-meter steel cable with PVC coating suits any height. The precision ball bearings ensure smooth, tangle-free rotation for fast-paced double unders. Perfect for home workouts, boxing training, and HIIT sessions.'
WHEN 'Stainless Steel Water Bottle 1L' THEN 'Stay hydrated throughout your workouts and daily activities with this durable 1-liter single-wall stainless steel water bottle. The food-grade 18/8 stainless steel construction is BPA-free, rust-proof, and doesnt impart any metallic taste to your water. The wide mouth makes it easy to add ice cubes and clean thoroughly, while the leak-proof screw cap prevents spills in your gym bag. The sleek brushed finish resists fingerprints and scratches. Lightweight yet incredibly tough for everyday use.'
WHEN 'Yoga Mat Premium 6mm' THEN 'Deepen your yoga and meditation practice with this premium 6mm thick yoga mat offering the perfect balance of cushioning and stability. The high-density TPE material provides excellent joint protection during kneeling poses and floor exercises, while the textured non-slip surface ensures a firm grip even during hot yoga or intense Pilates sessions. The lightweight, portable design comes with a carrying strap for easy transport to the studio or park. Free from PVC, latex, and harmful chemicals.'
WHEN 'Dumbbell Set 2-10kg' THEN 'Build strength and muscle at home with this versatile neoprene-coated dumbbell set ranging from 2kg to 10kg in five pairs. The soft neoprene coating provides a comfortable, non-slip grip while protecting your floors from scratches and damage. The hexagonal flat-bottom design prevents rolling and allows for stable storage. Each weight is color-coded for quick identification during circuit training. Perfect for progressive strength training, toning exercises, and rehabilitation workouts.'
WHEN 'Cricket Batting Gloves' THEN 'Protect your hands and improve your batting performance with these premium cricket batting gloves featuring high-density foam padding and reinforced finger protection. The lightweight yet durable construction allows natural hand movement and bat grip, while the breathable mesh back panel keeps your hands cool during long innings. The pre-curved finger design reduces hand fatigue, and the Velcro wrist strap ensures a secure, adjustable fit. Suitable for both right and left-handed batsmen.'
WHEN 'Exercise Ball 65cm' THEN 'Strengthen your core, improve balance, and enhance flexibility with this anti-burst exercise ball made from premium PVC material that supports up to 300kg. The 65cm size is ideal for users between 5ft 5in and 5ft 11in tall. Use it for Pilates, yoga, physiotherapy exercises, or as an active sitting alternative at your desk to improve posture throughout the workday. The textured anti-slip surface provides stability on any floor type. Comes with a hand pump and measuring tape for proper inflation.'
WHEN 'Pull Up Bar Doorframe' THEN 'Transform any standard doorframe into a complete upper body workout station with this heavy-duty pull-up bar. The innovative leverage-based mounting system requires no screws or drilling, making it perfect for renters. Supports up to 130kg and fits doorframes 65-95cm wide. The foam-padded grips in multiple positions allow you to perform pull-ups, chin-ups, hanging leg raises, and various grip variations. The compact design stores easily when not in use.'
ELSE description
END
WHERE category IN ('Home & Kitchen', 'Sports & Fitness');
