
-- Update Home & Kitchen product descriptions
UPDATE products SET description = 'Transform your kitchen with this premium electric kettle featuring 1.5-litre capacity, rapid boil technology, and auto shut-off for safety. The 304 stainless steel interior ensures no metallic taste in your beverages, while the concealed heating element is easy to clean. The ergonomic handle with soft-touch grip provides comfortable pouring, and the 360-degree swivel base allows both left and right-handed use. Perfect for making tea, coffee, instant noodles, and hot water for cooking. Energy-efficient with a power rating of 1500W, it boils water in under 3 minutes.' WHERE id = '3cb24982-3618-4e39-b925-6f8443978a7a';

UPDATE products SET description = 'Elevate your morning coffee ritual with this exquisite set of 6 handcrafted ceramic mugs, each holding 350ml of your favourite beverage. These mugs feature a premium matte finish with a reactive glaze technique that makes every piece unique. The double-walled ceramic construction keeps your drinks hot longer while remaining cool to the touch on the outside. Microwave and dishwasher safe, these mugs are as practical as they are beautiful. The wide handle design ensures a comfortable grip, and the flat bottom prevents tipping. Ideal for coffee, tea, hot chocolate, or even as decorative pieces on your kitchen shelf.' WHERE id = 'cdf8af0f-8b1a-416b-aa3b-f5ea92645f60';

UPDATE products SET description = 'Sleep in luxury with this king-size cotton bedsheet set featuring a 300-thread-count sateen weave that feels silky smooth against your skin. The set includes one flat sheet (108x108 inches) and two matching pillow covers (20x30 inches). Made from 100% long-staple combed cotton sourced from premium Indian mills, the fabric is pre-shrunk, fade-resistant, and gets softer with every wash. The deep-pocket fitted design accommodates mattresses up to 15 inches thick. Available in elegant solid colours that complement any bedroom decor, this bedsheet set transforms your bed into a five-star hotel experience.' WHERE id = '12d62c04-0f46-4b7e-9937-362f471d1607';

UPDATE products SET description = 'Breathe cleaner air with this advanced HEPA air purifier designed for rooms up to 500 sq ft. The 3-stage filtration system includes a pre-filter for dust and hair, a True HEPA H13 filter that captures 99.97% of particles as small as 0.3 microns, and an activated carbon filter that eliminates odours, smoke, and VOCs. Features a real-time air quality indicator with PM2.5 sensor, auto mode that adjusts fan speed based on air quality, sleep mode operating at whisper-quiet 24dB, and a child lock for safety. The filter replacement indicator ensures you always have optimal performance. Energy Star certified and ideal for allergy sufferers, pet owners, and urban homes.' WHERE id = 'e047ae96-3361-46e6-8cec-d348da61e9c9';

UPDATE products SET description = 'Keep your food fresh and organised with this set of 18 borosilicate glass containers featuring snap-lock airtight lids. Each container is made from thermal-shock resistant glass that can go directly from freezer to microwave without cracking. The BPA-free polypropylene lids create a leak-proof seal, making them perfect for carrying lunches and storing liquids. The set includes 6 rectangular (370ml, 640ml, 1050ml) and 3 round (400ml, 620ml, 950ml) containers with matching lids. Stackable design saves cabinet space, and the transparent glass lets you see contents at a glance. Dishwasher, microwave, and oven safe (without lids) up to 400°F.' WHERE id = '96f01501-8199-4542-8e1f-198b39de002d';

UPDATE products SET description = 'Bring nature indoors with this elegant set of 3 ceramic plant pots in graduating sizes (4-inch, 6-inch, and 8-inch diameter). Each pot features a contemporary matte finish with subtle geometric patterns and comes with a matching bamboo saucer tray to protect your surfaces. The drainage hole at the bottom prevents overwatering and root rot, while the bamboo tray catches excess water. These versatile pots are perfect for succulents, herbs, small ferns, and flowering plants. The neutral colour palette of white, sage green, and terracotta blends seamlessly with any interior design style — from minimalist modern to boho chic.' WHERE id = 'c7376330-de40-4ae1-a762-0f8fe872bee4';

UPDATE products SET description = 'Create a calming ambience with this luxurious set of 4 hand-poured soy wax candles in artisan glass jars. Each candle weighs 200g and offers up to 45 hours of clean, even burn time. The fragrances — French Lavender, Vanilla Bean, Eucalyptus Mint, and Sandalwood Rose — are crafted using premium essential oils and phthalate-free fragrance oils for a natural, non-toxic scent throw. The lead-free cotton wicks ensure a smoke-free burn, and the reusable glass jars make beautiful storage containers after the candle is finished. Perfect for meditation, relaxation, romantic dinners, or as a thoughtful gift.' WHERE id = '21bd348e-0f0d-411c-a2ed-d4191388a752';

UPDATE products SET description = 'Stay hydrated in style with this 1-litre insulated stainless steel water bottle featuring double-wall vacuum technology that keeps beverages cold for 24 hours or hot for 12 hours. The food-grade 18/8 stainless steel interior is BPA-free and does not retain flavours or odours. The leak-proof lid with a silicone seal and one-hand flip-top mechanism makes it ideal for gym workouts, office commutes, and outdoor adventures. The powder-coated exterior provides a sweat-free grip and scratch resistance. The wide mouth opening accommodates ice cubes and makes cleaning effortless. Comes with a carry loop and fits most standard cup holders.' WHERE id = '94935308-9b02-4057-a2fc-3b491fe46f7d';

-- Update Sports & Fitness product descriptions
UPDATE products SET description = 'Dominate the court with this professional-grade pair of badminton rackets featuring lightweight graphite frames weighing just 85g each. The isometric head shape provides a 32% larger sweet spot for more consistent and powerful shots. The rackets come pre-strung with high-tension nylon strings at 24 lbs for excellent control and repulsion. The PU grip with moisture-wicking technology ensures a firm hold during intense rallies. Includes 3 feather shuttlecocks and a premium carry case with shoulder strap. Suitable for intermediate to advanced players, these rackets offer the perfect balance of power, speed, and precision.' WHERE id = '088337bf-d5ca-4bd4-8806-de97e8bd6cb2';

UPDATE products SET description = 'Experience the crack of a perfectly timed cover drive with this Grade 1 English Willow cricket bat, handcrafted from premium unbleached willow cleft. The bat features 8-10 straight grains for exceptional performance and longevity. With a short handle and a balanced pickup weight of 1180g, it offers sublime stroke play for both front-foot and back-foot shots. The bat comes with a premium Sarawak cane handle wrapped in three layers of Singapore cane for superior shock absorption. The full-length concave spine and thick edges (38mm) provide a massive hitting zone. Pre-knocked and ready to play, with a complimentary padded bat cover included.' WHERE id = '9c154bb7-22cf-4972-97ab-578e5df5b3a2';

UPDATE products SET description = 'Build strength at home with this pair of premium rubber-coated cast iron dumbbells, each weighing 5kg. The hexagonal design prevents rolling on the floor and allows for unique exercises like renegade rows and push-up variations. The textured chrome-plated handle with knurled grip provides a secure, non-slip hold even during sweaty workouts. The durable rubber coating protects your floors and reduces noise during deadlifts and drops. These dumbbells are perfect for a wide range of exercises including bicep curls, shoulder presses, lunges, and chest flies. Ideal for home gyms, these versatile weights suit beginners and experienced lifters alike.' WHERE id = '4d577e9b-1986-4cc9-9bdc-a34e158262ce';

UPDATE products SET description = 'Accelerate your post-workout recovery with this high-density EVA foam roller measuring 18 inches in length and 6 inches in diameter. The textured surface features a multi-zone design with ridges, bumps, and smooth areas that mimic the hands of a massage therapist, targeting trigger points and releasing myofascial tension. Ideal for IT band relief, back pain, calf tightness, and hip flexor recovery. The lightweight yet firm construction supports users up to 120kg without losing shape. Use it before workouts to improve mobility and blood flow, or after exercise to reduce DOMS (delayed onset muscle soreness). Includes a free exercise guide with 15 foam rolling techniques.' WHERE id = '26b6c479-e1f8-4aa1-8f98-bd6fc4c8a7fe';

UPDATE products SET description = 'Play like the pros with this FIFA-quality match football featuring a thermally bonded seamless panel construction for a perfectly round shape and consistent flight trajectory. The premium PU outer casing provides superior touch and durability on both grass and artificial turf. The reinforced butyl bladder retains air pressure for weeks, ensuring the ball is always match-ready. Size 5 (official adult match size, circumference 68-70cm, weight 410-450g). The high-visibility design with reflective panels ensures excellent visibility in all lighting conditions. Water-resistant coating prevents the ball from becoming heavy in wet conditions. Comes with a ball pump and needle.' WHERE id = '0492e56c-7a9a-4a9a-b7b8-5423839aa45c';

UPDATE products SET description = 'Protect your hands and enhance your grip with these professional-grade gym gloves featuring genuine leather palms and breathable mesh backing. The integrated 12-inch wrist wraps with Velcro closure provide exceptional wrist support during heavy lifts like bench press, overhead press, and deadlifts. The 4mm gel padding on the palms absorbs shock and prevents calluses without compromising bar feel. The pull-tab finger loops make removal easy after a tough session. Available in sizes S to XL with an adjustable fit. Machine washable and quick-drying, these gloves are essential for serious weightlifters, CrossFit enthusiasts, and anyone who trains with barbells and dumbbells regularly.' WHERE id = 'db9b2e1c-91a2-4fe0-b254-f217b9f422e8';

UPDATE products SET description = 'Mix your protein shakes to perfection with this 700ml BPA-free Tritan plastic shaker bottle featuring a patented stainless steel mixing ball that breaks up even the thickest powders into smooth, lump-free drinks. The leak-proof screw-top lid with flip cap allows for easy one-hand drinking during or after workouts. The measurement markings on both sides (in ml and oz) ensure accurate mixing ratios every time. The wide mouth opening accommodates a standard supplement scoop and makes cleaning a breeze. Includes a detachable storage compartment at the bottom for carrying extra protein powder, vitamins, or pre-workout supplements. Dishwasher safe and available in 8 vibrant colours.' WHERE id = 'dd497e1e-c61b-4d2f-b0ba-de3635fa587a';

UPDATE products SET description = 'Take your fitness to the next level with this complete set of 5 resistance bands in progressive resistance levels: Extra Light (5 lbs), Light (10 lbs), Medium (20 lbs), Heavy (30 lbs), and Extra Heavy (40 lbs). Made from premium natural latex rubber, these bands are tear-resistant, skin-friendly, and maintain their elasticity even after thousands of stretches. Each band is colour-coded for easy identification and measures 12 inches in circumference. Perfect for warm-ups, rehabilitation exercises, glute activation, Pilates, yoga, and full-body strength training. Includes a mesh carry bag and a laminated exercise guide with 30 exercises targeting every major muscle group.' WHERE id = '6b448632-46aa-4888-a5e1-95d96cce0033';

UPDATE products SET description = 'Master the most effective cardio exercise with this premium adjustable skipping rope featuring precision ball bearings for smooth, tangle-free rotation at any speed. The lightweight aluminium handles with foam grips provide comfort during extended jump sessions, while the 3-metre steel cable (PVC coated) can be adjusted to any height with the simple screw mechanism. Suitable for single-unders, double-unders, and crossover tricks. An excellent calorie-burning tool that improves cardiovascular endurance, coordination, footwork, and agility. Used by boxers, MMA fighters, CrossFit athletes, and fitness enthusiasts worldwide. Weighs just 180g, making it highly portable for travel.' WHERE id = 'b492a5d0-0c29-419b-8bdc-f9cc5da278a0';

UPDATE products SET description = 'Elevate your yoga practice with this premium 6mm thick yoga mat made from eco-friendly TPE (Thermoplastic Elastomer) material that is free from PVC, latex, and toxic chemicals. The dual-layer construction features a textured non-slip surface on top for secure grip in all poses — even during hot yoga — and a ribbed bottom layer that grips the floor to prevent sliding. Measuring 183cm x 61cm, it provides ample space for all body types and yoga styles. The closed-cell structure repels sweat and moisture, preventing bacterial growth and making it easy to clean with a simple wipe. Lightweight at just 800g, it comes with a free carry strap for easy transport. Ideal for yoga, Pilates, meditation, and floor exercises.' WHERE id = '1fcea773-00a2-4ec5-a570-37bfa1e25ef7';
